spring.application.name=FileManagementService

spring.mongodb.uri=mongodb://localhost:1010/storage_db

storage.access-key=admin
storage.secret-key=admin123
storage.url=http://localhost:9000
storage.bucket=filemanagementservice
storage.storage-type=minio

server.port=8081

