spring.application.name=LMS


#app.security.jwt.private-key= ${JWT_PRIVATE_KEY:-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG...
#app.security.jwt.public-key= ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0B...}
#app.security.jwt.key-id= ${JWT_KEY_ID:auth-server-key-id}