spring.application.name=LMS

server.port=8081



spring.datasource.url=jdbc:postgresql://localhost:3030/AAAdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#spring.data.redis.host=localhost
#spring.data.redis.port=3030
#spring.data.redis.timeout=60000

spring.security.user.name=${APP_ADMIN_USER:admin}
spring.security.user.password=${APP_ADMIN_PASSWORD:admin789}



logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.web.servlet.error=DEBUG


spring.security.oauth2.client.registration.lms-module.provider=


